### ISSUE TITLE
LTO error

### ISSUE THREAD

**Issue by xootkama** [ElectroPerf/android_kernel_asus_sdm660-LTO#7]
aarch64-elf-ar:unit/main.o: plugin needed to handle lto object

**Comment by xootkama** [comment]
Hello this error was fixed k but how can I change clang

**Comment by tattwamashi** [comment]
@xootkama hey.. you can switch back to clang lto by disabling gcc lto and enabling clang lto in defconfig and then see if any more errors u get

**Comment by xootkama** [comment]
thanks
