### ISSUE TITLE
OS Not Booting

### ISSUE THREAD

**Issue by capriciousduck** [ElectroPerf/android_kernel_asus_sdm660-LTO#9]
Hi 

I flashed this kernel with the latest Havoc OS. After reboot Havoc OS keeps loading but doesn't completely boot -  boot logo loading and loading and loading. Can you help?

**Comment by tattwamashi** [comment]
Mention ur device and which build.. also provide boot logs

**Comment by capriciousduck** [comment]
My device is Asus Zenfone Max Pro M1 (X00TD) and I'm using Havoc-OS-v4.9-20211007-X00T-Official-GApps

How do I get boot logs? Through twrp?

**Comment by capriciousduck** [comment]
Any update?

**Comment by capriciousduck** [comment]
Hello. I realized that I flashed the P variant kernel when my Havoc OS is Android 11 (R). Is there a flashable zip (R variant) for X00TD?

**Comment by capriciousduck** [comment]
Build ID: RQ3A.210905.001

**Comment by tattwamashi** [comment]
> My device is Asus Zenfone Max Pro M1 (X00TD) and I'm using Havoc-OS-v4.9-20211007-X00T-Official-GApps
> 
> How do I get boot logs? Through twrp?

You should know how to take bootloop logs. Google it

**Comment by tattwamashi** [comment]
> Hello. I realized that I flashed the P variant kernel when my Havoc OS is Android 11 (R). Is there a flashable zip (R variant) for X00TD?

You know what the difference between them is?

**Comment by tattwamashi** [comment]
> Build ID: RQ3A.210905.001

I will be closing this issue because of unavailability of sufficient logs
